from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy, reverse


urlpatterns = [
    path('tydygfcfhsdhgfjdutgjh/', views.test, name='home2'),
    path('', views.home, name='home'),
    path('admin_panel/', views.admin_panel, name='amra_nashokota_korbo'),
    path('admin_panel/pending_orders/', views.admin_pending_orders, name='admin_pending_orders'),
    path('admin_panel/help/', views.admin_help, name='admin_help'),
    path('admin_panel/verify_users/', views.admin_verify_user, name='verify_users'),
    path('admin_panel/review_approval/', views.admin_review_msg_approval, name='admin_review_approval'),
    path('admin_panel/cash_flow/', views.admin_actual_flow, name='admin_cash_flow'),
    path('admin_panel/reserves/', views.admin_reserve, name='admin_reserve'),
    path('admin_panel/help/reply/<int:msg_id>', views.admin_reply, name='admin_reply'),
    path('admin_panel/completed_orders/', views.AdminCompletedOrder.as_view(), name='admin_completed_orders'),
    path('admin_panel/canceled_orders/', views.AdminCancceledOrder.as_view(), name='admin_canceled_orders'),
    path('admin_panel/unconfirmed_orders/', views.admin_unconfirmed_order, name='admin_unconfirmed_order'),
    path('admin_panel/waiting_orders/', views.admin_waiting_orders, name='admin_waiting_orders'),
    path('admin_panel/search_order/', views.admin_search_order, name='admin_search_order'),
    path('admin_panel/pending_orders/process_order_step1/<int:order_id>/', views.process_order_step1, name='process_order_step1'),
    path('admin_panel/waiting_orders/btc_order_processing/<int:order_id>/', views.btc_order_processing, name='btc_order_processing'),
    path('admin_panel/waiting_orders/btc_order_processing_step2/<int:order_id>/', views.btc_process_order_step2, name='btc_order_processing_step2'),
    path('admin_panel/pending_orders/process_order_step2/<int:order_id>/', views.process_order_step2, name='process_order_step2'),
    path('register/', views.register, name='register'),
    path('address/', views.address, name='address'),
    path('document_upload/', views.upload_doc, name='doc_upload'),
    path('profile/', views.profile, name='dashboard'),
    path('exchange_rate/', views.exchange_rate, name='exchange_rate'),
    path('terms_and_conditions/', views.terms_conditions, name='terms_conditions'),
    path('privacy_and_policy/', views.priv_poli, name='priv_poli'),
    path('AML_policy/', views.aml_poli, name='aml_poli'),
    path('refund_policy/', views.refund_poli, name='refund_poli'),
    path('about_us/', views.about_us, name='about_us'),
    path('help_center/', views.help_page, name='help'),
    path('upload_trxID/<int:order_id>/', views.up_trx_id, name='upload_trxid'),
    path('orders_processing_btc_wallet/<int:order_id>/', views.gen_btc_wallet, name='gen_btc_wallet'),
    path('btc_payment_successful/<int:order_id>/', views.btc_payment_after, name='btc_payment_after'),
    path('btc_order_status/<int:user_id>/<int:order_id>/', views.btc_payment_status, name='btc_payment_status'),
    path('btc_order_confirmation/<int:user_id>/<int:order_id>/', views.btc_payment_confirmation, name='btc_payment_confirmation'),
    path('completed_order/', views.CompletedOrder.as_view(), name = 'completed_order'),
    path('completed_order_details/<int:pk>', views.CompletedOrderDetails.as_view(), name = 'completed_order_details'),
    path('pending_transaction/', views.PendingOrder.as_view(), name = 'pending_transaction'),
    path('pending_transaction_details/<int:pk>', views.CompletedOrderDetails.as_view(), name = 'pending_transaction_details'),
    path('correct_trxID/<int:order_id>/', views.correct_trx_id, name='correct_trxid'),
    path('order_history/', views.order_history, name='order_history'),
    path('unconfirmed_order/', views.unconfirmed_order, name='unconfirmed_order'),
    path('pending_order/', views.pending_order, name='pending_order'),
    path('review/', views.ReviewMsgView.as_view(), name='review_msg'),
    path('address_edit/', views.AddressUpdateView.as_view(), name='address_update'),
    path('phone_edit/', views.PhoneUpdateView.as_view(), name='phone_update'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/password/change/', views.login_after_password_change, name='password_change'),
    path('accounts/password/change/done', auth_views.LogoutView.as_view(template_name='home/password_reset_complete.html'), name='password_change_done'),
    path('track_order/', views.track_order, name='track_order'),
    path('track_your_order/', views.track_your_order, name='track_your_order'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('ajax/get_info_update', views.update_page_dashboard, name = 'get_info_update'),
    path('ajax/search_result', views.search_ajax, name = 'search_filter'),
    path('ajax/admin_search_result', views.admin_search_ajax, name = 'admin_search_filter'),
    path('ajax/search_result_order_history', views.search_ajax_completed_order, name = 'search_filter_completed_order'),
    path('ajax/search_result_pending_order_history', views.search_ajax_pending_order, name = 'search_filter_pending_order'),
    path('settings/', views.settings, name = 'settings'),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/welcome_page.html'), name='logout'),
    # url(r'^$', views.home, name='home'),
    # url(r'^signup/$', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='home/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='home/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='home/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='home/password_reset_complete.html'), name='password_reset_complete'),
]

#path('paypal_payment03628800/', views.paypal_payment, name='paypal_payment'),