# Generated by Django 3.0.5 on 2020-04-24 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20200424_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_without_trxID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(max_length=100)),
                ('receive_at', models.CharField(max_length=100)),
                ('sent_amount', home.models.MinMaxFloat()),
                ('to_be_sent', home.models.MinMaxFloat()),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
