# Generated by Django 3.0.5 on 2020-04-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200424_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_without_trxid',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
