# Generated by Django 3.0.5 on 2020-04-24 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20200424_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_with_trxID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(max_length=100)),
                ('receive_at', models.CharField(max_length=100)),
                ('sent_amount', models.CharField(max_length=100)),
                ('to_be_sent', models.CharField(max_length=100)),
                ('trx_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('invalid', 'invalid'), ('done', 'done')], max_length=100)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='oreders_with_trxID',
        ),
    ]
