# Generated by Django 3.0.5 on 2020-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reserve_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('minim', models.FloatField()),
                ('maxim', models.FloatField()),
                ('reserve_am', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='reserve_balance',
        ),
    ]
