# Generated by Django 3.0.5 on 2020-04-25 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_auto_20200425_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('dhaka', 'Dhaka'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet'), ('khulna', 'Khulna'), ('chittagong', 'Chittagong'), ('barishal', 'Barishal')], max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('country_code', django_countries.fields.CountryField(max_length=2)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_status', models.CharField(choices=[('not_verified', 'not_verified'), ('verified', 'verified')], default='not_verified', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='profile_info',
        ),
    ]
