# Generated by Django 3.0.5 on 2020-05-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200502_1812'),
    ]

    operations = [

    ]
