# Generated by Django 3.0.5 on 2020-05-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200503_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_balances_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('minim', models.FloatField()),
                ('maxim', models.FloatField()),
                ('reserve_am', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('skril', models.FloatField()),
                ('neteller', models.FloatField()),
                ('paypal', models.FloatField()),
                ('payoneer', models.FloatField()),
                ('bkash', models.FloatField()),
                ('btcusd', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='reserve_balances',
        ),
    ]
