# Generated by Django 3.0.5 on 2020-05-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200504_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve_balances_rates',
            old_name='skril',
            new_name='skrill',
        ),
    ]
