# Generated by Django 3.0.5 on 2020-05-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_auto_20200507_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_with_trxid',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting for confirmation', 'waiting for confirmation'), ('invalid transaction id', 'invalid transaction id'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='Review_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=25000)),
                ('rating', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
