# Generated by Django 3.0.5 on 2020-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200508_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_without_trxid',
            name='receive_at',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('payoneer', 'Payoneer'), ('skrill', 'Skrill'), ('neteller', 'Neteller'), ('bkash', 'Bkash'), ('btcusd', 'BTC USD')], default='payoneer', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders_without_trxid',
            name='sent_from',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('payoneer', 'Payoneer'), ('skrill', 'Skrill'), ('neteller', 'Neteller'), ('bkash', 'Bkash'), ('btcusd', 'BTC USD')], default='paypal', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='profile_status',
            field=models.CharField(choices=[('not_verified', 'not_verified'), ('verified', 'verified'), ('pending', 'pending'), ('new', 'new')], default='new', max_length=100),
        ),
    ]
