# Generated by Django 3.0.5 on 2020-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200514_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_balances_rates',
            name='from_com',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reserve_balances_rates',
            name='to_com',
            field=models.FloatField(default=0.0),
        ),
    ]
