# Generated by Django 3.0.5 on 2020-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200516_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_balances_rates',
            name='from_com',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserve_balances_rates',
            name='to_com',
            field=models.FloatField(),
        ),
    ]
