# Generated by Django 3.0.5 on 2020-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200516_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_balances_rates',
            name='to_other',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reserve_balances_rates',
            name='to_same',
            field=models.FloatField(default=0.0),
        ),
    ]
