# Generated by Django 3.0.5 on 2020-05-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20200516_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve_balances_rates',
            name='to_other',
        ),
        migrations.RemoveField(
            model_name='reserve_balances_rates',
            name='to_same',
        ),
    ]
