# Generated by Django 3.0.5 on 2020-05-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20200517_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversion_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('to_bkash', models.FloatField()),
            ],
        ),
    ]
