# Generated by Django 3.0.5 on 2020-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_review_msg_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_with_trxid',
            name='transaction_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='review_msg',
            name='length',
            field=models.IntegerField(),
        ),
    ]
