# Generated by Django 3.0.5 on 2020-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20200517_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_with_trxid',
            name='transaction_amount',
            field=models.FloatField(),
        ),
    ]
