# Generated by Django 3.0.5 on 2020-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20200517_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_with_trxid',
            name='sent_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_with_trxid',
            name='to_be_sent',
            field=models.FloatField(),
        ),
    ]
