# Generated by Django 3.0.5 on 2020-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_btc_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_with_trxid',
            name='admin_receiving_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order_with_trxid',
            name='admin_sending_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='our_ids',
            name='rcv_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='our_ids',
            name='reserve',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='our_ids',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
    ]
