# Generated by Django 3.0.5 on 2020-06-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20200601_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_without_trxid',
            name='admin_receiving_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
