# Generated by Django 3.0.5 on 2020-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_order_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='state',
            field=models.CharField(choices=[('unseen', 'unseen'), ('replied', 'replied')], default='unseen', max_length=100),
        ),
    ]
