# Generated by Django 3.0.5 on 2020-06-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
