# Generated by Django 3.0.5 on 2020-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_msg',
            name='state',
            field=models.CharField(choices=[('hide', 'hide'), ('show', 'show')], default='hide', max_length=100),
        ),
    ]
