# Generated by Django 3.0.5 on 2020-06-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_review_msg_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_msg',
            name='state',
            field=models.CharField(choices=[('hide', 'hide'), ('show', 'show'), ('uncensored', 'uncensored')], default='hide', max_length=100),
        ),
    ]
