# Generated by Django 3.0.5 on 2020-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20200616_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_with_trxid',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting for confirmation', 'waiting for confirmation'), ('invalid transaction id', 'invalid transaction id'), ('completed', 'completed'), ('canceled', 'canceled'), ('unconfirmed', 'unconfirmed')], default='pending', max_length=100),
        ),
    ]
