# Generated by Django 3.0.5 on 2020-06-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20200617_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_with_trxid',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting for confirmation', 'waiting for confirmation'), ('invalid transaction id', 'invalid transaction id'), ('completed', 'completed'), ('canceled', 'canceled'), ('unconfirmed', 'unconfirmed'), ('confirmed', 'confirmed')], default='pending', max_length=100),
        ),
    ]
