# Generated by Django 3.0.5 on 2020-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20200618_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_with_trxid',
            name='admin_rcv_btc_wallet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order_with_trxid',
            name='admin_send_btc_wallet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
