# Generated by Django 3.0.5 on 2020-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20200618_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='we_rcv',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='we_send',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10),
        ),
    ]
