# Generated by Django 3.0.5 on 2020-06-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20200618_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_processed_by',
            name='made_status',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
